{% set name = "giddy" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af5e53e798564aea909f2efa0e177a0625ab2a230e23b05c0e8468242a90475c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - scipy >=1.3.0
    - libpysal >=4.0.1
    - mapclassify >=2.1.1
    - esda >=2.1.1
    - quantecon >=0.4.7

test:
  imports:
    - giddy

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: GeospatIal Distribution DYnamics (giddy) in PySAL

  description: |
    Giddy is an open-source python library for the analysis of dynamics of longitudinal spatial 
    data. Originating from the spatial dynamics module in PySAL (Python Spatial Analysis Library), 
    it is under active development for the inclusion of newly proposed analytics that consider the 
    role of space in the evolution of distributions over time.
  doc_url: http://pysal.org/giddy
  dev_url: https://github.com/pysal/giddy

extra:
  recipe-maintainers:
    - weikang9009
    - knaaptime
    - sjsrey
