{% set name = "giddy" %}
{% set version = "2.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/giddy-{{ version }}.tar.gz
  sha256: 004ec587eb7b75d9f717efd9b018a9f95f55d30d9768e2bb9cdb86ae7bdb7592

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<310]

requirements:
  host:
    - python
    - wheel
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python
    - esda >=2.4
    - libpysal >=4.8
    - mapclassify >=2.5
    - quantecon >=0.7
    - scipy >=1.8

test:
  imports:
    - giddy
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs giddy.tests  # [py<312]
  requires:
    - pip
    - pytest
    # To enable tests for py>312 need to rebuild split.
    - splot  # [py<312]

about:
  home: https://pysal.org
  summary: GeospatIal Distribution DYnamics (giddy) in PySAL
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Giddy is an open-source python library for the analysis of dynamics of longitudinal spatial 
    data. Originating from the spatial dynamics module in PySAL (Python Spatial Analysis Library), 
    it is under active development for the inclusion of newly proposed analytics that consider the 
    role of space in the evolution of distributions over time.
  doc_url: https://pysal.org/giddy
  dev_url: https://github.com/pysal/giddy

extra:
  recipe-maintainers:
    - weikang9009
    - knaaptime
    - sjsrey
