travis:
  secure:
    BINSTAR_TOKEN: lSrYh10VoofHp0gdxhbeCFtBCWEfEw7eYlA1nfsmm0SPBtGjJAtDqfmadb0quTUs5skr816KEUvQQMLv/Xc+s2kRhmN0OD5BZyjjqB3qzW/5B5vyJNkaN64zVfG/zFlBRa/bsCFtQsQoszOCkybBzxAr3slIUw5uoW3d45CHnyqUgiQAmwGo48Hw6pfagJQ00iTlvR3SV89XecvmfbcOoLdNepq3+feUkvzALsKMAitXq8yF/sgWXPUvodeoYTe1BM55FVZtO+q2sh8SzqDfr4+ihJLth65EnLGE4dSptr316daTc9EBNWJfbKphifEr5Kgg8svOymRlEfl5lz6A96Oxa+vTLbvmQHDAGWK74oem47kej+YSk5qbgzThSVgWHkT/PEMAG95KsenBp4JuE+K/doN36ayDOZhxJDsxWeYQLQDKGZup++zpNbazqpladc88ghapHbo9B+yrDw1kJlUwE/LiIzPbb+JM26W1O+tkRisYmh3jYs3KtvEDy4ojBN/S6crerq9Q7GbpN6AdnyMGtEluSmtSa2iaZxdo1ryHgxM7SGEklDfO4xXhIN41fWu5SzFCKoVMzR30SdNcmGTou7sRNPWnYWbXT258aW3rDHCjiPI6epvTKApkrafQRSMkbwB/R34n9EEJd6hjbbECBjAD1lDM3QqXsK+i7aA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
